source 'https://rubygems.org'

group :lint do
  gem 'foodcritic', '~> 5.0', '>= 5.0.0'
  gem 'rubocop'
end

group :unit do
  gem 'chefspec', '~> 4.1'
  gem 'berkshelf', '~> 7.0', '>= 7.0.2'
end

group 'integration' do
  gem 'kitchen-docker', '~> 1.6.0'
  gem 'kitchen-sync', '>= 1.1.0'
  gem 'kitchen-vagrant', '~> 1.5', '>= 1.5.1'
  gem 'minitest-chef-handler'
  gem 'test-kitchen', '~> 2.5', '>= 2.5.2'
  gem 'vagrant-wrapper'
end
